name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/ansible
